<html lang="nl" version="HTML+RDFa 1.1" prefix="og: http://ogp.me/ns#"
itemscope="itemscope" itemtype="http://schema.org/Article" class=" js  js no-touch opacity svg json"
style="">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="content-language" content="nl">
        <meta http-equiv="cache-control" content="Public">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta http-equiv="X-Powered-By" content="DocPad">
        <title>
            Risico- &amp; Pensioenadvies | Tredius.nl
        </title>
        <meta name="robots" content="all">
        <meta name="rivist-after" content="1 days">
        <meta name="rating" content="General">
        <meta name="author" content="Solobit &amp; Edberry Creative">
        <meta name="email" content="info@tredius.nl">
        <meta name="copyright" content="2013 © Tredius.nl">
        <meta name="keywords" content="belasting, advies, accountancy, pensioenbelasting, bedrijfsadministratie">
        <meta name="description" content="Bij Tredius hebben we de behoefte om het            MKB landschap te veranderen: Vrijheid, Onafhankelijkheid en            Zelfstandigheid, voor iedere ondernemer.">
        <meta property="og:title" content="Risico- &amp; Pensioenadvies | Tredius.nl">
        <meta property="og:url" content="/diensten/risicoadvies-en-verzekeringen.html">
        <meta property="og:type">
        <meta property="og:image" content="/media/afbeeldingen/bedrijfslogo.png">
        <meta itemprop="name" content="s:WebPage">
        <meta itemprop="description" content="Bij Tredius hebben we de behoefte om het            MKB landschap te veranderen: Vrijheid, Onafhankelijkheid en            Zelfstandigheid, voor iedere ondernemer.">
        <meta itemprop="image" content="/media/afbeeldingen/bedrijfslogo.png">
        <meta name="viewport" content="width=device-width, initial-scale=0.7">
        <link rel="stylesheet" href="/stijlen/algemeen.css?1366221798.448">
        <link rel="stylesheet" href="/stijlen/circlemenu.css">
        <link rel="shortcut icon" href="/media/afbeeldingen/favicon.png" type="image/png">
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Dosis:400,500,600|Open+Sans:400italic,600italic,700italic,400,600,700&quot;">
        <script type="text/javascript" async="" src="http://www.google-analytics.com/ga.js">
        </script>
        <script src="/assets/modernizr-custom.js">
        </script>
        <script src="/assets/ender.min.js">
        </script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
        </script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js">
        </script>
        <script src="/assets/jquery.colorbox.js">
        </script>
        <script src="/assets/jquery.easing.min.js">
        </script>
        <style type="text/css">
        </style>
    </head>

    <body xmlns:s="http://schema.org/" xmlns:gr="http://purl.org/goodrelations/v1#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:vcard="http://www.w3.org/2006/vcard/ns#"
    xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:v="http://rdf.data-vocabulary.org/#" xmlns:pto="http://www.productontology.org/id/"
    xmlns:wn="http://xmlns.com/wordnet/1.6/">
        <section id="paginakop">
            <header itemscope="itemscope" itemtype="gr:BusinessEntity" about="#company">
                <div property="gr:legalName" content="Tredius">
                </div>
                <a href="http://www.tredius.nl" alt="Terug naar startpagina" rel="foaf:page"
                resource="http://www.tredius.nl"><img width="160" height="59" rel="foaf:logo" alt="Ga terug naar Tredius.nl hoofdpagina" title="Tredius.nl" src="/media/afbeeldingen/bedrijfslogo.png" resource="/media/afbeeldingen/bedrijfslogo.png"></a>
            </header>
            <aside>
                <a class="login knop" href="https://login.twinfield.com/">Inloggen</a>
            </aside>
            <ul class="meganizr menu-klasse" role="menubar" itemscope="itemscope"
            itemtype="s:SiteNavigationElement">
                <li role="menuitem" aria-haspopup="false" aria-labelledby="m1-home">
                    <a id="m1-home" href="http://www.tredius.nl" tabindex="1">HOME</a>
                </li>
                <li role="menuitem" aria-haspopup="false" aria-labelledby="m1-wzw">
                    <a id="m1-wzw" href="/overtuiging.html" tabindex="2">WIE ZIJN WE</a>
                </li>
                <li class="menu-uitvouwen menu-breedst" role="menuitem" aria-haspopup="true"
                aria-labelledby="m1-dienst">
                    <a id="m1-dienst" href="#" tabindex="3">ONZE DIENSTEN</a>
                    <div class="menu-inhoud">
                        <div class="menu-groep">
                            <h3 role="menuitem">
                                BELASTING
                            </h3>
                            <ul class="menu-links" role="menu">
                                <li>
                                    <a role="menuitem" tabindex="4" href="/diensten/belastingadvies.html">Belastingadvies</a>
                                </li>
                                <li>
                                    <a role="menuitem" tabindex="5" href="/diensten/pensioen.html">Pensioen</a>
                                </li>
                                <li>
                                    <a role="menuitem" tabindex="6" href="/diensten/estateplanning.html">Estate Planning</a>
                                </li>
                            </ul>
                        </div>
                        <div class="menu-groep">
                            <h3 role="menuitem">
                                ACCOUNTANCY
                            </h3>
                            <ul class="menu-links" role="menu">
                                <li>
                                    <a role="menuitem" tabindex="7" href="/diensten/accountancy.html">Accountancy</a>
                                </li>
                                <li>
                                    <a role="menuitem" tabindex="8" href="/diensten/salaris-en-personeel.html">Salaris &amp; Personeelszaken</a>
                                </li>
                                <li>
                                    &nbsp;
                                </li>
                            </ul>
                        </div>
                        <div class="menu-groep">
                            <h3 role="menuitem">
                                JURIDISCH
                            </h3>
                            <ul class="menu-links" role="menu">
                                <li>
                                    <a role="menuitem" tabindex="9" href="/diensten/juridisch-advies.html">Juridisch Advies</a>
                                </li>
                                <li>
                                    <a role="menuitem" tabindex="10" href="/diensten/juridisch-abonnement.html">Juridisch Abonnement</a>
                                </li>
                                <li>
                                    &nbsp;
                                </li>
                            </ul>
                        </div>
                        <div class="menu-groep">
                            <h3 role="menuitem">
                                RISICO- &amp; PENSIOENADVIES
                            </h3>
                            <ul class="menu-links" role="menu">
                                <li>
                                    <a role="menuitem" tabindex="11" href="/diensten/risicoadvies-en-verzekeringen.html">Risicoadvies &amp; Verzekeringen</a>
                                </li>
                                <li>
                                    <a role="menuitem" tabindex="11" href="/diensten/pensioenadvies.html">Pensioenadvies</a>
                                </li>
                                <li>
                                    <a role="menuitem" tabindex="11" href="/diensten/overstapservice.html">Schoenendoos Overstapservice</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="menu-uitvouwen menu-smal" role="menuitem" aria-haspopup="true"
                aria-labelledby="m1-tt">
                    <a id="m1-tt" tabindex="12" href="/diensten/debiteurenbeheer/">DEBITEUREN</a>
                    <ul role="menu">
                        <li>
                            <a role="menuitem" tabindex="13" href="/diensten/debiteurenbeheer/">Debiteurenbeheer</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="14" href="/diensten/debiteurenbeheer/stappenplan.html">Onze werkwijze</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="15" href="/diensten/debiteurenbeheer/abonnement.html">Abonnement</a>
                        </li>
                    </ul>
                </li>
                <li class="menu-uitvouwen menu-smal" role="menuitem" aria-haspopup="true"
                aria-labelledby="m1-tt">
                    <a id="m1-tt" tabindex="14" href="/t-time/">T-TIME</a>
                    <ul role="menu">
                        <li>
                            <a role="menuitem" tabindex="15" href="/t-time/#1">Tredius vertelt...</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="17" href="/t-time/#2">Nieuwsbrief</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="16" href="/t-time/#3">Onze columns</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="18" href="/t-time/#4">Specials</a>
                        </li>
                    </ul>
                </li>
                <li class="menu-uitvouwen menu-smal" role="menuitem" aria-haspopup="true"
                aria-labelledby="m1-werk">
                    <a id="m1-werk" tabindex="19" href="/werken-bij/">WERKEN BIJ</a>
                    <ul role="menu">
                        <li>
                            <a role="menuitem" tabindex="20" href="/werken-bij/index.html">Werken bij Tredius</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="21" href="/werken-bij/vacatures.html">Vacatures</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="22" href="/werken-bij/stages.html">Stages</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="23" href="/werken-bij/wie-ben-jij.html">Wie ben jij?</a>
                        </li>
                    </ul>
                </li>
                <li class="menu-uitvouwen menu-smal" role="menuitem" aria-haspopup="true"
                aria-labelledby="m1-locatie">
                    <a id="m1-locatie" tabindex="24" href="#">VESTIGINGEN</a>
                    <ul role="menu">
                        <li>
                            <a role="menuitem" tabindex="25" href="/vestigingen/alkmaar.html">Alkmaar</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="26" href="/vestigingen/haarlem.html">Haarlem</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="27" href="/vestigingen/monnickendam.html">Monnickendam</a>
                        </li>
                        <li>
                            <a role="menuitem" tabindex="28" href="/vestigingen/purmerend.html">Purmerend</a>
                        </li>
                    </ul>
                </li>
                <li role="menuitem" aria-haspopup="false" aria-labelledby="m1-contact">
                    <a id="m1-contact" tabindex="29" href="/contact.html">CONTACT</a>
                </li>
            </ul>
        </section>
        <header id="bannier" role="banner" aria-labelledby="label_titel" style="background: url('/media/afbeeldingen/bg_pensioen.jpg') repeat-x;">
            <h1 id="label_titel" title="Tredius">
            </h1>
            <div id="menucontext" itemscope="itemscope" itemtype="s:WebPage">
                <div class="pagina-info">
                    <h1 id="pagina_titel" itemprop="name">
                        Risico- &amp; Pensioenadvies
                    </h1>
                    <h2 id="pagina_subtitel" itemprop="about">
                        Risicoadvies &amp; Verzekeringen
                    </h2>
                    <p itemprop="description">
                    </p>
                    <meta itemprop="keywords">
                    <meta itemprop="creator" content="Tredius">
                </div>
            </div>
        </header>
        <section id="pagina" role="main">
            <article id="risico-en-advies" class="inhoud">
                <p>
                    Ondernemen is vrijheid, onafhankelijkheid en zelfstandigheid. Ondernemen
                    is ook risico’s nemen. Kleine vrijheden betekent kleine risico’s. Voor
                    deze kleine dagelijkse risico’s heeft u waarschijnlijk amper advies nodig,
                    dat weet u heel goed zelf. Grote vrijheiden betekent ook grotere risico’s.
                    Hoe fijn is het dan om een adviseur te hebben die de risico’s weet en u
                    kort en bondig in heldere taal kan uitleggen welke risico’s u als ondernemer
                    loopt. Met als doel het behouden van uw vrijheid.
                </p>
                <p>
                    Naast een goed advies is Tredius 100% onafhankelijk assurantietussenpersoon.
                    Zo kunt u bij ons al uw risico’s verzekeren tegen een goede prijs. Om te
                    zorgen dat gedurende de looptijd van een verzekering of lijfrente u zorgeloos
                    kunt blijven ondernemen, zijn de risicoadviseurs uw eerste aanspreekpunt.
                    Een bekend gezicht en vertrouwde stem. Dus geen klantenservice waar u niet
                    goed geholpen wordt. Ook hier staat zorgeloos ondernemen voorop.
                </p>
                <p>
                    Hieronder enkele voorbeelden.
                </p>
                <blockquote>
                    <figure>
                        <img src="/media/afbeeldingen/icon_voorbeeld.png" height="86" width="86">
                        <figcaption>
                            Voorbeeld I
                        </figcaption>
                    </figure>
                    <p>
                        Onze risicoadviseurs zorgen voor het inzicht dat zorgt dat u weet welke
                        risico’s u als ondernemer loopt. Zo heeft een ondernemer met een eigen
                        bedrijfspand een brandverzekering. Een geruststellende gedachte als de
                        boel in vlammen op gaat.
                    </p>
                    <p>
                        Maar hoe zit het met uw personeel, de lopende kosten en crediteuren. Al
                        deze kosten moet u blijven betalen, terwijl u geen geld kan verdienen doordat
                        het pand in vlammen is opgegaan. Een afgebrand pand is niet binnen 1 week
                        opgebouwd. Het duurt soms wel een jaar voordat u weer helemaal up en running
                        bent.
                    </p>
                    <p>
                        Een verzekering tegen dit soort schade kan een uitkomst bieden. Veel belangrijker
                        vinden wij het dat u als ondernemer weet, welke risico’s u loopt en of
                        het voor u interessant is om te verzekeren. Want dat is lang niet altijd
                        nodig.
                    </p>
                </blockquote>
                <blockquote>
                    <figure>
                        <img src="/media/afbeeldingen/icon_voorbeeld.png" height="86" width="86">
                        <figcaption>
                            Voorbeeld II
                        </figcaption>
                    </figure>
                    <p>
                        Een andere situatie is als u net begint als ondernemer. Is het dan echt
                        wel nodig om direct te gaan verzekeren tegen arbeidsongeschiktheid? De
                        aanloopkosten zijn al hoog en het geld stroomt niet direct binnen. Onze
                        risico adviseurs hebben hiervoor andere oplossingen, die betaalbaar zijn,
                        maar toch die geruststellende gedachte meebrengen dat het risico van arbeidsongeschiktheid
                        is gedekt.
                    </p>
                </blockquote>
                <blockquote>
                    <figure>
                        <img src="/media/afbeeldingen/icon_voorbeeld.png" height="86" width="86">
                        <figcaption>
                            Voorbeeld III
                        </figcaption>
                    </figure>
                    <p>
                        U als ondernemer heeft ambitie en dat betekent dat het bedrijf gaat groeien.
                        U kunt het niet meer alleen aan en dus neemt u personeel aan. Maar wat
                        als er met het personeel wat gebeurd. Ze worden ziek of hebben tijdens
                        een sportwedstrijd in het weekend een enkel gebroken en zijn 8 weken uit
                        de roulatie. U als ondernemer zit dan met de gebakken peren, want er wordt
                        niet gewerkt, maar u moet wel het salaris blijven betalen.
                    </p>
                    <p>
                        Het is dus goed om vooraf te bepalen of u deze risico’s wilt verzekeren
                        en in welke vorm. Heeft u wat buffers, dan is het wellicht niet nodig.
                        Iedere situatie is hierin anders. Onze risicoadviseurs helpen u graag om
                        u hierin meer duidelijkheid te geven.
                    </p>
                </blockquote>
                <div class="contactblok">
                    <hr class="stippellijn">
                    <p>
                        Mocht u advies willen over uw risico’s, groot of klein:
                    </p>
                    <p>
                        aarzel dan niet contact op te nemen met onze risicoadviseur
                    </p>
                    <address itemscope="itemscope" itemtype="s:ContactPoint" class="contactpersoon">
                        <span itemprop="name" class="pocnaam">
                            Luuk Oosting
                        </span>
                        <strong itemprop="telephone" class="poctelefoon">
                            0299 651 987
                        </strong>
                    </address>
                </div>
            </article>
        </section>
        <div class="mediaband">
            <section id="multimedia" role="complementary">
                <aside class="nieuwsbrief">
                    <h3>
                        Kwartaal Nieuwsbrief
                    </h3>
                    <p>
                        Meld je aan voor de Tredius nieuwsbrief
                    </p>
                    <form class="nieuwsbrief" role="form" name="form_api" method="post" action="@site.frm.nieuwsbrief">
                        <input id="email" class="invoer" type="email" name="Email" size="20" placeholder="Uw emailadres...">
                        <a class="knop versturen klein" href="#">Aanmelden »</a>
                    </form>
                </aside>
                <aside class="video" itemscope="itemscope" itemtype="s:VideoObject">
                    <iframe id="embedVimeo-speler1" src="http://player.vimeo.com/video/55429476?api=1&amp;player_id=embedVimeo-speler1&amp;title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;color=e31741"
                    width="300" height="169" frameborder="0">
                    </iframe>
                </aside>
                <aside class="video" itemscope="itemscope" itemtype="s:VideoObject">
                    <iframe id="embedVimeo-speler2" src="http://player.vimeo.com/video/55430952?api=1&amp;player_id=embedVimeo-speler2&amp;title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;color=e31741"
                    width="300" height="169" frameborder="0">
                    </iframe>
                </aside>
            </section>
        </div>
        <script>
        var __slice = Array.prototype.slice;
var __hasProp = Object.prototype.hasOwnProperty;
var __bind = function(fn, me) {
        return function() {
            return fn.apply(me, arguments);
        };
    };
var __extends = function(child, parent) {
        for (var key in parent) {
            if (__hasProp.call(parent, key)) child[key] = parent[key];
        }
        function ctor() {
            this.constructor = child;
        }
        ctor.prototype = parent.prototype;
        child.prototype = new ctor;
        child.__super__ = parent.prototype;
        return child;
    };
var __indexOf = Array.prototype.indexOf ||
function(item) {
    for (var i = 0, l = this.length; i < l; i++) {
        if (this[i] === item) return i;
    }
    return -1;
};
(function() {
    return $(document).ready(function() {
        var addEvent, log, ready;

        log = function() {
            var args;

            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return console.log.apply(console, args);
        };
        addEvent = function(element, eventName, callback) {
            if (element.addEventListener) {
                return element.addEventListener(eventName, callback, false);
            } else {
                return element.attachEvent(eventName, callback, false);
            }
        };
        return ready = function(player_id) {
            var froogaloop, onFinish, onPlay, player1, player2;

            onPlay = function() {
                return froogaloop.addEvent("play", function(data) {
                    return log("vimeo: afspelen");
                });
            };
            onFinish = function() {
                return froogaloop.addEvent("finish", function(data) {
                    return log("vimeo: stoppen");
                });
            };
            log("vimeo: gereed!");
            froogaloop = $f(player_id);
            onPlay();
            onFinish();
            player1 = $("#embedVimeo-speler1")[0];
            player2 = $("#embedVimeo-speler2")[0];
            $f(player1).addEvent("ready", ready);
            return $f(player2).addEvent("ready", ready);
        };
    });
/*
  # Put together the URL

  # This function puts the video on the page
  embedVideo = (video) ->
    document.getElementById("embed").innerHTML = unescape(video.html)

  # This function loads the data from Vimeo
  init = ->
    js = document.createElement("script")
    js.setAttribute "type", "text/javascript"
    js.setAttribute "src", url
    document.getElementsByTagName("head").item(0).appendChild js

  # This is the URL of the video you want to load
  videoUrl = "http://www.vimeo.com/7100569"

  # This is the oEmbed endpoint for Vimeo (we're using JSON)
  endpoint = "http://www.vimeo.com/api/oembed.json"

  # Tell Vimeo what function to call
  callback = "embedVideo"

  url = endpoint + "?url=" + encodeURIComponent(videoUrl) + "&callback=" + callback + "&width=640"

  # Call our init function when the page loads
  window.onload = init
  */

}).call(this);
        </script>
        <footer id="snelkoppelingen" role="contentinfo">
            <section>
                <h4 id="menuVoet1">
                    ONZE DIENSTEN
                </h4>
                <ul role="navigation" aria-labelledby="menuVoet1">
                    <li>
                        <a href="/diensten/accountancy.html">Accountancy</a>
                    </li>
                    <li>
                        <a href="/diensten/belastingadvies.html">Belastingadvies</a>
                    </li>
                    <li>
                        <a href="/diensten/estateplanning.html">Estate Planning</a>
                    </li>
                    <li>
                        <a href="/diensten/juridisch-abonnement.html">Juridisch Abonnement</a>
                    </li>
                    <li>
                        <a href="/diensten/juridisch-advies.html">Juridisch Advies</a>
                    </li>
                    <li>
                        <a href="/diensten/pensioen.html">Pensioen</a>
                    </li>
                    <li>
                        <a href="/diensten/risicoadvies-en-verzekeringen.html">Risicoadvies &amp; Verzekeringen</a>
                    </li>
                    <li>
                        <a href="/diensten/salaris-en-personeel.html">Salarisadministratie</a>
                    </li>
                    <li>
                        <a href="/diensten/overstapservice.html">Schoenendoos Overstapservice</a>
                    </li>
                </ul>
            </section>
            <section>
                <h4 id="menuVoet2">
                    WERKEN BIJ TREDIUS
                </h4>
                <ul role="navigation" aria-labelledby="menuVoet2">
                    <li>
                        <a href="/werken-bij/stages.html">Stageplekken</a>
                    </li>
                    <li>
                        <a href="/werken-bij/vacatures.html">Vacatures</a>
                    </li>
                    <li>
                        <a href="/werken-bij/index.html">Werken bij Tredius</a>
                    </li>
                    <li>
                        <a href="/werken-bij/wie-ben-jij.html">Wie ben jij?</a>
                    </li>
                </ul>
            </section>
            <section>
                <h4 id="menuVoet3">
                    OVER TREDIUS
                </h4>
                <ul role="navigation" aria-labelledby="menuVoet3">
                    <li>
                        <a href="/contact.html">Contactformulier</a>
                    </li>
                    <li>
                        <a href="/overtuiging.html">Over Tredius</a>
                    </li>
                    <li>
                        <a href="/t-time/index.html">T-Time</a>
                    </li>
                </ul>
            </section>
        </footer>
        <footer id="paginavoet">
            <aside>
                2013 © Tredius.nl
            </aside>
            <aside>
                <ul>
                    <li>
                        <a href="/overig/voorwaarden.html">Voorwaarden</a>
                    </li>
                    <li>
                        &nbsp; | &nbsp;
                        <a href="/overig/privacy.html">Privacybeleid</a>
                    </li>
                    <li>
                        &nbsp; | &nbsp;
                        <a href="/overig/handelsregister.html">Handelsregister</a>
                    </li>
                </ul>
            </aside>
        </footer>
        <script>
        var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-39413290-1']);
_gaq.push(['_trackPageview']);
(function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
})();
        </script>
        <script defer="defer" src="/assets/jquery.cookie.js">
        </script>
        <script defer="defer" src="/assets/jquery.circlemenu.js">
        </script>
        <script defer="defer" src="/assets/vimeo.froogaloop2.min.js">
        </script>
        <script defer="defer" src="/app.js">
        </script>
        <div id="cboxOverlay" style="display: none;">
        </div>
        <div id="colorbox" class="" role="dialog" tabindex="-1" style="display: none;">
            <div id="cboxWrapper">
                <div>
                    <div id="cboxTopLeft" style="float: left;">
                    </div>
                    <div id="cboxTopCenter" style="float: left;">
                    </div>
                    <div id="cboxTopRight" style="float: left;">
                    </div>
                </div>
                <div style="clear: left;">
                    <div id="cboxMiddleLeft" style="float: left;">
                    </div>
                    <div id="cboxContent" style="float: left;">
                        <div id="cboxTitle" style="float: left;">
                        </div>
                        <div id="cboxCurrent" style="float: left;">
                        </div>
                        <button id="cboxPrevious">
                        </button>
                        <button id="cboxNext">
                        </button>
                        <button id="cboxSlideshow">
                        </button>
                        <div id="cboxLoadingOverlay" style="float: left;">
                        </div>
                        <div id="cboxLoadingGraphic" style="float: left;">
                        </div>
                        <button id="cboxClose">
                        </button>
                    </div>
                    <div id="cboxMiddleRight" style="float: left;">
                    </div>
                </div>
                <div style="clear: left;">
                    <div id="cboxBottomLeft" style="float: left;">
                    </div>
                    <div id="cboxBottomCenter" style="float: left;">
                    </div>
                    <div id="cboxBottomRight" style="float: left;">
                    </div>
                </div>
            </div>
            <div style="position: absolute; width: 9999px; visibility: hidden; display: none;">
            </div>
        </div>
        <div id="cruxpad_notify_div" style="display: none;">
            <iframe id="cruxpad_notify_frame" src="http://www.cruxlight.com/html/error-dialog.html?dispMsg=&amp;&amp;url=http://tredius.nl/diensten/risicoadvies-en-verzekeringen.html"
            frameborder="0" style="display: none;">
            </iframe>
        </div>
        <cruxpad_wrapper id="cruxpad_wrapper" style="">
            <iframe id="cruxpad_iframe" src="http://www.cruxlight.com/html/0.1.5/summary.html?url=http://tredius.nl/diensten/risicoadvies-en-verzekeringen.html&amp;&amp;pluginId=94a7a85bd154d1bdbb7fe2e7a74dcfe&amp;&amp;popupDisableFlag=N&amp;&amp;theme=default"
            class="cruxpad_layer" frameborder="0" style="">
            </iframe>
        </cruxpad_wrapper>
        <script id="hiddenlpsubmitdiv" style="display: none;">
        </script>
        <script>
        try {
    for (var lastpass_iter = 0; lastpass_iter < document.forms.length; lastpass_iter++) {
        var lastpass_f = document.forms[lastpass_iter];
        if (typeof(lastpass_f.lpsubmitorig2) == "undefined") {
            lastpass_f.lpsubmitorig2 = lastpass_f.submit;
            lastpass_f.submit = function() {
                var form = this;
                var customEvent = document.createEvent("Event");
                customEvent.initEvent("lpCustomEvent", true, true);
                var d = document.getElementById("hiddenlpsubmitdiv");
                for (var i = 0; i < document.forms.length; i++) {
                    if (document.forms[i] == form) {
                        d.innerText = i;
                    }
                }
                d.dispatchEvent(customEvent);
                form.lpsubmitorig2();
            }
        }
    }
} catch (e) {}
        </script>
    </body>
    <div id="PvuLzRKcTOxlTcfP6Wm3EJQoNJ" class="q4TdVLmJBsa5IgSo5h0gUM4" style="display: none;">
    </div>
    <div id="K6BrWjmbVNd0li1ruT2rPS" class="q4TdVLmJBsa5IgSo5h0gUM4" style="display: none;">
    </div>
    <div id="uW5uEaS1lF4jLQHKyrs" class="q4TdVLmJBsa5IgSo5h0gUM4" style="display: none;">
    </div>

</html>
