
<!-- Tables are your main poison to format email consistently. Set table widths inside cells and in most cases
reset cellpadding, cellspacing, and border to zero.

Use nested tables as a way to space effectively in the message.

If you were developing for the web near 2k, this might look familiar -->

<table cellpadding="0" cellspacing="0" border="0" align="center" class="$grid$">
  <tr>

    <td width="200" valign="top"></td>

    <td width="200" valign="top"></td>

    <td width="200" valign="top"></td>

  </tr>
</table>
