<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<meta name="viewport" content="width=device-width, initial-scale=$scale$"/>

  <title>$title()$</title>

	<style type="text/css">

    $reset()$

    /* Move to inline classes, you may want to clear this out hence (parens)() */
    $(main)()$

    $queries()$

	</style>

    $ie-mobile7()$

    $msoffice-9()$

</head>


<body>

<!-- Wrapper: control width and background consistently, instead of using body attributes. -->

<table cellpadding="0" cellspacing="0" border="0" id="backgroundTable" style="$wrapper$">
	<tr>
		<td valign="top">


      <!-- Inner table main body, overridable from application -->


      $(body)()$




		</td>
	</tr>
</table>

</body>
</html>

